
# Configuration file for the project
#
# Goon into to TOML here: https://learnxinyminutes.com/docs/toml/ 
#


[llm]
default_model = "gpt_35_openai"

[embeddings]
cache = "/home/tcl/hf_models"
#default_model = "OpenAI"
#default_model = "dangvantuan/sentence-camembert-base"
default_model = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

[vector_store]
default= "Chroma"
path = "/home/tcl/chromadb"

[documents]
base = "${HOME}/prj/genai-training/use_case_data"

