
# Configuration file for the project
#

[llm]
default_model = "gpt_3_openai"

[embeddings]
cache = "/home/tcl/hf_models"
#default_model = "OpenAI"
#default_model = "dangvantuan/sentence-camembert-base"
default_model = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
vector_store_path = "/home/tcl/chromadb"

[documents]
base = "${HOME}/prj/genai-training/use_case_data"

