#cSpell: disable
[tool.poetry]
name = "genai-blueprint"
version = "0.1.2"
description = ""
authors = ["Thierry Caminel <thierry.caminel@eviden.com>"]
readme = "README.md"
requires-poetry = ">=2.0"

[tool.poetry.urls]
Homepage = "https://github.com/tcaminel-pro/genai-blueprint"
Repository = "https://github.com/tcaminel-pro/genai-blueprint"


[tool.poetry.dependencies]
python = ">=3.12,<3.13"
pydantic = "^2.7.0"
devtools = "^0.12.2"
loguru = "^0.7.3"
typer = "^0.13.0"
tabulate = "^0.9.0"
python-dotenv = "^1.0.1"
json-repair = "^0.30.0"
fastapi = "^0.115.6"

langchain = "^0.3.14"
langchain-core = "^0.3.29"
langchain-community = "^0.3.14"
langchain-experimental = "^0.3.4"
langchain-openai = "^0.2.9"
langchain-huggingface = "^0.1.2"
langchain-ollama = "^0.2.0"
langgraph = "^0.2.63"
langserve = "^0.3.1"
langchainhub = "^0.1.21"
langchain-groq = "^0.2.1"
langchain-chroma = "^0.2.0"
chromadb = "^0.5.17"
#httpx = "^0.27.0"
litellm = "^1.58.2"

[tool.poetry.group.instrumentation]  # Install: poetry install --with ai_extra
optional = false

[tool.poetry.group.instrumentation.dependencies]
arize-phoenix = "^7.7.2"
opentelemetry-sdk = "^1.29.0"
opentelemetry-exporter-otlp = "^1.29.0"
openinference-instrumentation-langchain = "^0.1.29"
openinference-instrumentation-smolagents = "^0.1.0"
openinference-instrumentation-crewai = "^0.1.3"


[tool.poetry.group.ui]  # Install: poetry install --with ai_extra
optional = false

[tool.poetry.group.ui.dependencies]
streamlit = "^1.32.1"
uvicorn = "^0.27.1"
sse-starlette = "^2.1.0"
# pygraphviz = "^1.13"


[tool.poetry.group.ai_extra]  # Install: poetry install --with ai_extra
optional = false

[tool.poetry.group.ai_extra.dependencies]
gpt-researcher = "^0.10.11"
unidecode = "^1.3.8"
browser-use = "^0.1.23"
smolagents = "^1.3.0"
langchain-mcp = "^0.1.0"
tavily-python = "^0.3.3"
duckduckgo-search = "^6.1.6"

[tool.poetry.group.demos]  # Install: poetry install --with demos
optional = false

[tool.poetry.group.demos.dependencies]
bs4 = "^0.0.2"
lark = "^1.1.9"
plotly = "^5.22.0"
yfinance = "^0.2.38"
rank-bm25 = "^0.2.2"
spacy = "^3.7.4"
matplotlib = "^3.9.0"
sqlalchemy = "^2.0.29"
abbreviations = "^0.2.5"
enchant = "^0.0.1"
pypdf = "^5.1.0"
giskard = "^2.15.5"
crewai = {extras = ["tools"], version = "^0.95.0"}


[tool.poetry.group.transformers]  # Install: poetry install --with transformers
# Warning: require 5 GB at least + storage for models
optional = false

[tool.poetry.group.transformers.dependencies]
langchain-huggingface = "^0.1.2"
sentence-transformers = "^2.6.1"
accelerate = "^0.30.1"


[tool.poetry.group.dev.dependencies]
ruff = "^0.9.1"
pytest = "^8.1.1"
ipykernel = "^6.29.4"
ipywidgets = "^8.1.2"

[tool.ruff]
builtins = ["ic", "debug"]
line-length = 120  # default is 88

[tool.ruff.lint]
select = [ "E", "F", "I" ]
ignore = [ "E501" ]

[tool.ruff.lint.pycodestyle]
ignore-overlong-task-comments = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pyright]
pythonVersion = "3.12"
pythonPlatform = "Linux"
reportTypedDictNotRequiredAccess = false  # Avoid warnings in LangGraph

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

