[tool.poetry]
name = "genai-training"
version = "0.1.0"
description = ""
authors = ["Thierry Caminel <thierry.caminel@eviden.com>"]
readme = "README.md"
#packages = [{include = "genai-training"}]

[tool.poetry.urls]
Homepage = "https://github.com/tcaminel-pro/genai-training"
Repository = "https://github.com/tcaminel-pro/genai-training"


[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pydantic = "^2.7.0"
langchain = "^0.1.20"
langchain-core = "^0.1.52"
langgraph = "^0.0.49"
langchain-community = "^0.0.38"
langchainhub = "^0.1.15"
langchain-experimental = "^0.0.58"
langchain-groq = "^0.1.3"
langchain-openai = "^0.1.3"
#langchain-openai = "^0.0.5"
langchain-chroma = "^0.1.0"
litellm = "^1.37.9"
lunary = "^1.0.17"
devtools = "^0.12.2"
loguru = "^0.7.2"
chromadb = "^0.4.24"
fastapi = "^0.110.1"
uvicorn = "^0.27.1"
httpx = "^0.27.0"
typer = "^0.9.0"
streamlit = "^1.32.1"
sqlalchemy = "^2.0.29"
bs4 = "^0.0.2"
sentence-transformers = {version = "^2.6.1", optional = true }  #poetry install --extras "sentence-transformers" or poetry install --all-extras
#crewai = "^0.28.8"
lark = "^1.1.9"
pyyaml = "^6.0.1"
tiktoken = "^0.5.2"
tavily-python = "^0.3.3"
pygraphviz = "^1.12"
grandalf = "^0.8"
langserve = "^0.1.1"
diagrams = "^0.23.4"
plotly = "^5.22.0"
yfinance = "^0.2.38"
sse-starlette = "^2.1.0"
langchain-google-genai = "^1.0.3"
tabulate = "^0.9.0"
langchain-google-vertexai = "^1.0.3"


[tool.poetry.group.extra]  # Install : poetry install --with extra 
optional = false

[tool.poetry.group.extra.dependencies]
sentence-transformers = "^2.6.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
ipykernel = "^6.29.4"
ruff = "^0.1.4"

[tool.ruff]
select = [ "E", "F", "I" ]
ignore = [ "E501" ]

[tool.pyright]
pythonVersion = "3.10"
pythonPlatform = "Linux"
reportTypedDictNotRequiredAccess = false  # Avoid warnings in LangGraph

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

